# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1aFhp_TLsJ640kBWB6qtGHbnSHfRJpoXw
"""

import os
from pathlib import Path
import shutil

# 创建主目录
project_dir = Path("ai_stock_app")
project_dir.mkdir(exist_ok=True)

# streamlit_app.py
(project_dir / "streamlit_app.py").write_text('''
import streamlit as st
import pandas as pd
import matplotlib.pyplot as plt
import yfinance as yf
from datetime import date

st.set_page_config(page_title="📈 AI美股组合", layout="wide")
st.title("📈 每日 AI 美股组合推荐")

tickers = ['AAPL', 'MSFT', 'NVDA', 'TSLA']
prices = yf.download(tickers, period="6mo")['Adj Close']
today = date.today()

for ticker in tickers:
    st.subheader(f"📌 {ticker} 走势图")
    data = prices[ticker]
    fig, ax = plt.subplots(figsize=(6, 3))
    ax.plot(data.index, data.values)
    st.pyplot(fig)
''')

# daily_ai_portfolio_email.py
(project_dir / "daily_ai_portfolio_email.py").write_text('''
import smtplib
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText

SMTP_SERVER = 'smtp.gmail.com'
SMTP_PORT = 587
EMAIL_ADDRESS = 'your_email@gmail.com'
EMAIL_PASSWORD = 'your_app_password'
RECIPIENT_EMAIL = 'recipient@example.com'

def send_email(subject, body):
    msg = MIMEMultipart()
    msg['From'] = EMAIL_ADDRESS
    msg['To'] = RECIPIENT_EMAIL
    msg['Subject'] = subject
    msg.attach(MIMEText(body, 'plain'))

    with smtplib.SMTP(SMTP_SERVER, SMTP_PORT) as server:
        server.starttls()
        server.login(EMAIL_ADDRESS, EMAIL_PASSWORD)
        server.send_message(msg)
''')

# 股票池
(project_dir / "spy_components.csv").write_text("Symbol\nAAPL\nMSFT\nNVDA\nTSLA\nGOOGL")

# requirements.txt
(project_dir / "requirements.txt").write_text("streamlit\nyfinance\npandas\nnumpy\nmatplotlib\nscikit-learn")

# README.md
(project_dir / "README.md").write_text('''
# AI Stock Portfolio Recommender

A daily AI-based US stock recommender with Streamlit UI & email support.

## Features
- AI-based daily portfolio
- Email alerts
- Streamlit web app
- Chart + financial data

## How to use

```bash
pip install -r requirements.txt
streamlit run streamlit_app.py